spring.datasource.url=jdbc:h2:mem:tasknovadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Security
jwt.secret=9a67a84e2a874092b3a9712a6a12b6f12c8a14d5e239a58b29c91b8d76a23f18e97f0a82b3d
jwt.expiration=86400000
